// Code generated by protoc-gen-go. DO NOT EDIT.
// source: configCenter.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CfgReq struct {
	UserName             string          `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	EnvNum               string          `protobuf:"bytes,2,opt,name=EnvNum,proto3" json:"EnvNum,omitempty"`
	Target               []string        `protobuf:"bytes,3,rep,name=Target,proto3" json:"Target,omitempty"`
	File                 *CompressedFile `protobuf:"bytes,4,opt,name=File,proto3" json:"File,omitempty"`
	CfgVersions          []*CfgVersion   `protobuf:"bytes,5,rep,name=CfgVersions,proto3" json:"CfgVersions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CfgReq) Reset()         { *m = CfgReq{} }
func (m *CfgReq) String() string { return proto.CompactTextString(m) }
func (*CfgReq) ProtoMessage()    {}
func (*CfgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_configCenter_0b65ccd828dff226, []int{0}
}
func (m *CfgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CfgReq.Unmarshal(m, b)
}
func (m *CfgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CfgReq.Marshal(b, m, deterministic)
}
func (dst *CfgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CfgReq.Merge(dst, src)
}
func (m *CfgReq) XXX_Size() int {
	return xxx_messageInfo_CfgReq.Size(m)
}
func (m *CfgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CfgReq.DiscardUnknown(m)
}

var xxx_messageInfo_CfgReq proto.InternalMessageInfo

func (m *CfgReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *CfgReq) GetEnvNum() string {
	if m != nil {
		return m.EnvNum
	}
	return ""
}

func (m *CfgReq) GetTarget() []string {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *CfgReq) GetFile() *CompressedFile {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *CfgReq) GetCfgVersions() []*CfgVersion {
	if m != nil {
		return m.CfgVersions
	}
	return nil
}

type CfgVersion struct {
	Version              string          `protobuf:"bytes,1,opt,name=Version,proto3" json:"Version,omitempty"`
	Confs                []*ConfigScheme `protobuf:"bytes,2,rep,name=Confs,proto3" json:"Confs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CfgVersion) Reset()         { *m = CfgVersion{} }
func (m *CfgVersion) String() string { return proto.CompactTextString(m) }
func (*CfgVersion) ProtoMessage()    {}
func (*CfgVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_configCenter_0b65ccd828dff226, []int{1}
}
func (m *CfgVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CfgVersion.Unmarshal(m, b)
}
func (m *CfgVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CfgVersion.Marshal(b, m, deterministic)
}
func (dst *CfgVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CfgVersion.Merge(dst, src)
}
func (m *CfgVersion) XXX_Size() int {
	return xxx_messageInfo_CfgVersion.Size(m)
}
func (m *CfgVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_CfgVersion.DiscardUnknown(m)
}

var xxx_messageInfo_CfgVersion proto.InternalMessageInfo

func (m *CfgVersion) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *CfgVersion) GetConfs() []*ConfigScheme {
	if m != nil {
		return m.Confs
	}
	return nil
}

type ConfigScheme struct {
	ConfigName           string     `protobuf:"bytes,1,opt,name=ConfigName,proto3" json:"ConfigName,omitempty"`
	Clusters             []*Cluster `protobuf:"bytes,2,rep,name=Clusters,proto3" json:"Clusters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ConfigScheme) Reset()         { *m = ConfigScheme{} }
func (m *ConfigScheme) String() string { return proto.CompactTextString(m) }
func (*ConfigScheme) ProtoMessage()    {}
func (*ConfigScheme) Descriptor() ([]byte, []int) {
	return fileDescriptor_configCenter_0b65ccd828dff226, []int{2}
}
func (m *ConfigScheme) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigScheme.Unmarshal(m, b)
}
func (m *ConfigScheme) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigScheme.Marshal(b, m, deterministic)
}
func (dst *ConfigScheme) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigScheme.Merge(dst, src)
}
func (m *ConfigScheme) XXX_Size() int {
	return xxx_messageInfo_ConfigScheme.Size(m)
}
func (m *ConfigScheme) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigScheme.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigScheme proto.InternalMessageInfo

func (m *ConfigScheme) GetConfigName() string {
	if m != nil {
		return m.ConfigName
	}
	return ""
}

func (m *ConfigScheme) GetClusters() []*Cluster {
	if m != nil {
		return m.Clusters
	}
	return nil
}

type Cluster struct {
	ClusterName          string   `protobuf:"bytes,1,opt,name=ClusterName,proto3" json:"ClusterName,omitempty"`
	Nodes                []*Node  `protobuf:"bytes,2,rep,name=Nodes,proto3" json:"Nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cluster) Reset()         { *m = Cluster{} }
func (m *Cluster) String() string { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()    {}
func (*Cluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_configCenter_0b65ccd828dff226, []int{3}
}
func (m *Cluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster.Unmarshal(m, b)
}
func (m *Cluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster.Marshal(b, m, deterministic)
}
func (dst *Cluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster.Merge(dst, src)
}
func (m *Cluster) XXX_Size() int {
	return xxx_messageInfo_Cluster.Size(m)
}
func (m *Cluster) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster proto.InternalMessageInfo

func (m *Cluster) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *Cluster) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type Node struct {
	GlobalId             string   `protobuf:"bytes,1,opt,name=GlobalId,proto3" json:"GlobalId,omitempty"`
	LocalId              string   `protobuf:"bytes,2,opt,name=LocalId,proto3" json:"LocalId,omitempty"`
	Template             string   `protobuf:"bytes,3,opt,name=Template,proto3" json:"Template,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_configCenter_0b65ccd828dff226, []int{4}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetGlobalId() string {
	if m != nil {
		return m.GlobalId
	}
	return ""
}

func (m *Node) GetLocalId() string {
	if m != nil {
		return m.LocalId
	}
	return ""
}

func (m *Node) GetTemplate() string {
	if m != nil {
		return m.Template
	}
	return ""
}

type CfgResp struct {
	Status               string          `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	SliceData            []string        `protobuf:"bytes,2,rep,name=SliceData,proto3" json:"SliceData,omitempty"`
	File                 *CompressedFile `protobuf:"bytes,3,opt,name=File,proto3" json:"File,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CfgResp) Reset()         { *m = CfgResp{} }
func (m *CfgResp) String() string { return proto.CompactTextString(m) }
func (*CfgResp) ProtoMessage()    {}
func (*CfgResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_configCenter_0b65ccd828dff226, []int{5}
}
func (m *CfgResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CfgResp.Unmarshal(m, b)
}
func (m *CfgResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CfgResp.Marshal(b, m, deterministic)
}
func (dst *CfgResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CfgResp.Merge(dst, src)
}
func (m *CfgResp) XXX_Size() int {
	return xxx_messageInfo_CfgResp.Size(m)
}
func (m *CfgResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CfgResp.DiscardUnknown(m)
}

var xxx_messageInfo_CfgResp proto.InternalMessageInfo

func (m *CfgResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *CfgResp) GetSliceData() []string {
	if m != nil {
		return m.SliceData
	}
	return nil
}

func (m *CfgResp) GetFile() *CompressedFile {
	if m != nil {
		return m.File
	}
	return nil
}

type CompressedFile struct {
	FileName             string   `protobuf:"bytes,1,opt,name=FileName,proto3" json:"FileName,omitempty"`
	FileData             []byte   `protobuf:"bytes,2,opt,name=FileData,proto3" json:"FileData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompressedFile) Reset()         { *m = CompressedFile{} }
func (m *CompressedFile) String() string { return proto.CompactTextString(m) }
func (*CompressedFile) ProtoMessage()    {}
func (*CompressedFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_configCenter_0b65ccd828dff226, []int{6}
}
func (m *CompressedFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompressedFile.Unmarshal(m, b)
}
func (m *CompressedFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompressedFile.Marshal(b, m, deterministic)
}
func (dst *CompressedFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompressedFile.Merge(dst, src)
}
func (m *CompressedFile) XXX_Size() int {
	return xxx_messageInfo_CompressedFile.Size(m)
}
func (m *CompressedFile) XXX_DiscardUnknown() {
	xxx_messageInfo_CompressedFile.DiscardUnknown(m)
}

var xxx_messageInfo_CompressedFile proto.InternalMessageInfo

func (m *CompressedFile) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *CompressedFile) GetFileData() []byte {
	if m != nil {
		return m.FileData
	}
	return nil
}

func init() {
	proto.RegisterType((*CfgReq)(nil), "pb.CfgReq")
	proto.RegisterType((*CfgVersion)(nil), "pb.CfgVersion")
	proto.RegisterType((*ConfigScheme)(nil), "pb.ConfigScheme")
	proto.RegisterType((*Cluster)(nil), "pb.Cluster")
	proto.RegisterType((*Node)(nil), "pb.Node")
	proto.RegisterType((*CfgResp)(nil), "pb.CfgResp")
	proto.RegisterType((*CompressedFile)(nil), "pb.CompressedFile")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConfigCenterClient is the client API for ConfigCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConfigCenterClient interface {
	GET(ctx context.Context, in *CfgReq, opts ...grpc.CallOption) (*CfgResp, error)
	POST(ctx context.Context, in *CfgReq, opts ...grpc.CallOption) (*CfgResp, error)
	DELETE(ctx context.Context, in *CfgReq, opts ...grpc.CallOption) (*CfgResp, error)
	PUT(ctx context.Context, in *CfgReq, opts ...grpc.CallOption) (*CfgResp, error)
}

type configCenterClient struct {
	cc *grpc.ClientConn
}

func NewConfigCenterClient(cc *grpc.ClientConn) ConfigCenterClient {
	return &configCenterClient{cc}
}

func (c *configCenterClient) GET(ctx context.Context, in *CfgReq, opts ...grpc.CallOption) (*CfgResp, error) {
	out := new(CfgResp)
	err := c.cc.Invoke(ctx, "/pb.ConfigCenter/GET", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configCenterClient) POST(ctx context.Context, in *CfgReq, opts ...grpc.CallOption) (*CfgResp, error) {
	out := new(CfgResp)
	err := c.cc.Invoke(ctx, "/pb.ConfigCenter/POST", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configCenterClient) DELETE(ctx context.Context, in *CfgReq, opts ...grpc.CallOption) (*CfgResp, error) {
	out := new(CfgResp)
	err := c.cc.Invoke(ctx, "/pb.ConfigCenter/DELETE", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configCenterClient) PUT(ctx context.Context, in *CfgReq, opts ...grpc.CallOption) (*CfgResp, error) {
	out := new(CfgResp)
	err := c.cc.Invoke(ctx, "/pb.ConfigCenter/PUT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigCenterServer is the server API for ConfigCenter service.
type ConfigCenterServer interface {
	GET(context.Context, *CfgReq) (*CfgResp, error)
	POST(context.Context, *CfgReq) (*CfgResp, error)
	DELETE(context.Context, *CfgReq) (*CfgResp, error)
	PUT(context.Context, *CfgReq) (*CfgResp, error)
}

func RegisterConfigCenterServer(s *grpc.Server, srv ConfigCenterServer) {
	s.RegisterService(&_ConfigCenter_serviceDesc, srv)
}

func _ConfigCenter_GET_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CfgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCenterServer).GET(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ConfigCenter/GET",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCenterServer).GET(ctx, req.(*CfgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigCenter_POST_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CfgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCenterServer).POST(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ConfigCenter/POST",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCenterServer).POST(ctx, req.(*CfgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigCenter_DELETE_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CfgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCenterServer).DELETE(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ConfigCenter/DELETE",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCenterServer).DELETE(ctx, req.(*CfgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigCenter_PUT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CfgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCenterServer).PUT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ConfigCenter/PUT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCenterServer).PUT(ctx, req.(*CfgReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConfigCenter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ConfigCenter",
	HandlerType: (*ConfigCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GET",
			Handler:    _ConfigCenter_GET_Handler,
		},
		{
			MethodName: "POST",
			Handler:    _ConfigCenter_POST_Handler,
		},
		{
			MethodName: "DELETE",
			Handler:    _ConfigCenter_DELETE_Handler,
		},
		{
			MethodName: "PUT",
			Handler:    _ConfigCenter_PUT_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "configCenter.proto",
}

func init() { proto.RegisterFile("configCenter.proto", fileDescriptor_configCenter_0b65ccd828dff226) }

var fileDescriptor_configCenter_0b65ccd828dff226 = []byte{
	// 429 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0xc5, 0x71, 0xae, 0xe3, 0xaa, 0x42, 0xf3, 0x80, 0xac, 0x0a, 0x55, 0x66, 0x91, 0x4a, 0x9e,
	0x22, 0x14, 0x3e, 0xc1, 0x35, 0x05, 0x51, 0x85, 0x6a, 0x93, 0x02, 0xaf, 0x4e, 0x32, 0x31, 0x91,
	0x6c, 0xaf, 0xeb, 0xdd, 0xf0, 0x31, 0x7c, 0x04, 0xdf, 0x88, 0xf6, 0xe6, 0xba, 0x2f, 0x79, 0xca,
	0x9c, 0x73, 0x66, 0x4f, 0x46, 0x73, 0xc6, 0x80, 0x3b, 0x51, 0x1f, 0x8e, 0x45, 0x4a, 0xb5, 0xa2,
	0x76, 0xd1, 0xb4, 0x42, 0x09, 0x1c, 0x34, 0x5b, 0xf6, 0x2f, 0x80, 0x71, 0x7a, 0x28, 0x38, 0x3d,
	0xe1, 0x15, 0x4c, 0x1f, 0x25, 0xb5, 0xab, 0xbc, 0xa2, 0x38, 0x48, 0x82, 0xf9, 0x8c, 0x77, 0x18,
	0xdf, 0xc0, 0x38, 0xab, 0xff, 0xac, 0x4e, 0x55, 0x3c, 0x30, 0x8a, 0x43, 0x9a, 0xdf, 0xe4, 0x6d,
	0x41, 0x2a, 0x0e, 0x93, 0x50, 0xf3, 0x16, 0xe1, 0x0d, 0x0c, 0x3f, 0x1f, 0x4b, 0x8a, 0x87, 0x49,
	0x30, 0x8f, 0x96, 0xb8, 0x68, 0xb6, 0x8b, 0x54, 0x54, 0x4d, 0x4b, 0x52, 0xd2, 0x5e, 0x2b, 0xdc,
	0xe8, 0xf8, 0x11, 0xa2, 0xf4, 0x50, 0xfc, 0xa0, 0x56, 0x1e, 0x45, 0x2d, 0xe3, 0x51, 0x12, 0xce,
	0xa3, 0xe5, 0xa5, 0x69, 0xef, 0x68, 0xde, 0x6f, 0x61, 0x2b, 0x80, 0x67, 0x88, 0x31, 0x4c, 0x5c,
	0xe9, 0x46, 0xf6, 0x10, 0x6f, 0x60, 0x94, 0x8a, 0xfa, 0x20, 0xe3, 0x81, 0xf1, 0x7c, 0x6d, 0x47,
	0xd0, 0x3b, 0x58, 0xef, 0x7e, 0x53, 0x45, 0xdc, 0xca, 0xec, 0x27, 0x5c, 0xf4, 0x69, 0xbc, 0x06,
	0xb0, 0xb8, 0xb7, 0x87, 0x1e, 0x83, 0x1f, 0x60, 0x9a, 0x96, 0x27, 0xa9, 0xa8, 0xf5, 0xd6, 0x91,
	0xb1, 0xb6, 0x1c, 0xef, 0x44, 0xf6, 0x0d, 0x26, 0xae, 0xc6, 0x04, 0x22, 0x57, 0xf6, 0x4c, 0xfb,
	0x14, 0x5e, 0xc3, 0x68, 0x25, 0xf6, 0xe4, 0x2d, 0xa7, 0xda, 0x52, 0x13, 0xdc, 0xd2, 0xec, 0x17,
	0x0c, 0x75, 0xa1, 0x33, 0xba, 0x2b, 0xc5, 0x36, 0x2f, 0xbf, 0xee, 0x7d, 0x46, 0x1e, 0xeb, 0x5d,
	0xdc, 0x8b, 0x9d, 0x91, 0x6c, 0x48, 0x1e, 0xea, 0x57, 0x1b, 0xaa, 0x9a, 0x32, 0x57, 0x14, 0x87,
	0xf6, 0x95, 0xc7, 0xac, 0x80, 0x89, 0xc9, 0x5f, 0x36, 0x3a, 0xcc, 0xb5, 0xca, 0xd5, 0x49, 0x3a,
	0x6b, 0x87, 0xf0, 0x2d, 0xcc, 0xd6, 0xe5, 0x71, 0x47, 0xb7, 0xb9, 0xca, 0xcd, 0x80, 0x33, 0xfe,
	0x4c, 0x74, 0x51, 0x87, 0xe7, 0xa3, 0x66, 0x5f, 0xe0, 0xf2, 0x25, 0xaf, 0xc7, 0xd2, 0xbf, 0xfd,
	0x83, 0xf3, 0xd8, 0x6b, 0xee, 0x2f, 0x83, 0xf9, 0x05, 0xef, 0xf0, 0xf2, 0x6f, 0xe0, 0x33, 0xb3,
	0xe7, 0x8c, 0x09, 0x84, 0x77, 0xd9, 0x06, 0xc1, 0xdd, 0x0d, 0xa7, 0xa7, 0xab, 0xa8, 0xab, 0x65,
	0xc3, 0x5e, 0xe1, 0x3b, 0x18, 0x3e, 0x7c, 0x5f, 0x9f, 0x6d, 0x79, 0x0f, 0xe3, 0xdb, 0xec, 0x3e,
	0xdb, 0x64, 0xe7, 0x9a, 0x12, 0x08, 0x1f, 0x1e, 0xcf, 0xd9, 0x6c, 0xc7, 0xe6, 0xdb, 0xfa, 0xf4,
	0x3f, 0x00, 0x00, 0xff, 0xff, 0x6e, 0xa3, 0x91, 0xd8, 0x71, 0x03, 0x00, 0x00,
}
